### ISSUE TITLE
Lower limit to downvotes

### ISSUE THREAD

**Issue by tvlooy** [Intracto/ITRLibrary#6]
eg: -5 means post will be deleted

**Comment by pix-art** [comment]
So if a post hits -5 insta delete it? or clean up all posts below -5 each 5 min?

**Comment by tvlooy** [comment]
each 5 min is cool too but requires an extra cronjob. Best thing to do is to not show posts if they have < -5 votes so people also can't add the URL again and again. The system knows about that URL ;-)
